In [1]:
import numpy as np

In [2]:
vector = np.arange(1, 11)

In [3]:
("Вектор:", vector)

('Вектор:', array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [4]:
matrix_3x3 = np.zeros((3, 3))
("Матриця 3x3:\n", matrix_3x3)

('Матриця 3x3:\n',
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [5]:
matrix_5x5 = np.random.randint(1, 11, (5, 5))
("Матриця 5x5:\n", matrix_5x5)

('Матриця 5x5:\n',
 array([[1, 5, 9, 5, 1],
        [8, 9, 8, 2, 3],
        [3, 2, 3, 6, 4],
        [3, 1, 9, 8, 9],
        [1, 3, 1, 5, 5]], dtype=int32))

In [6]:
matrix_4x4 = np.random.rand(4, 4)
("Матриця 4x4:\n", matrix_4x4)

('Матриця 4x4:\n',
 array([[0.61240221, 0.53126598, 0.12957555, 0.03995588],
        [0.62110553, 0.35125623, 0.77325496, 0.14342859],
        [0.83137842, 0.12755048, 0.60553801, 0.05791097],
        [0.84041092, 0.09408688, 0.3230451 , 0.78723545]]))

In [7]:
array1 = np.random.randint(1, 11, 5)
array2 = np.random.randint(1, 11, 5)

("Масив 1:", array1)
("Масив 2:", array2)
("Додавання:", array1 + array2)
("Віднімання:", array1 - array2)
("Множення:", array1 * array2)

('Множення:', array([70,  7, 18, 72, 50], dtype=int32))

In [8]:
vector1 = np.random.random(7)
vector2 = np.random.random(7)

scalar_product = np.dot(vector1, vector2)
("Вектор 1:", vector1)
("Вектор 2:", vector2)
("Скалярний добуток:", scalar_product)

('Скалярний добуток:', np.float64(2.0251158192698777))

In [9]:
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 3))

result = np.dot(matrix1, matrix2)
("Матриця 1:\n", matrix1)
("Матриця 2:\n", matrix2)
("Результат множення:\n", result)

('Результат множення:\n',
 array([[130,  95,  80],
        [170, 120, 108]], dtype=int32))

In [10]:
matrix_3x3 = np.random.randint(1, 11, (3, 3))
inverse_matrix = np.linalg.inv(matrix_3x3)
("Матриця 3x3:\n", matrix_3x3)
("Обернена матриця:\n", inverse_matrix)

('Обернена матриця:\n',
 array([[-1.56097561,  1.19512195,  0.53658537],
        [ 0.17073171, -0.14634146,  0.09756098],
        [ 0.36585366, -0.17073171, -0.2195122 ]]))

In [11]:
matrix_4x4 = np.random.rand(4, 4)
transposed_matrix = matrix_4x4.T
("Матриця 4x4:\n", matrix_4x4)
("Транспонована матриця:\n", transposed_matrix)

('Транспонована матриця:\n',
 array([[0.38536903, 0.56588088, 0.70923574, 0.5584559 ],
        [0.8167709 , 0.93259447, 0.7761147 , 0.76863717],
        [0.79353232, 0.02863911, 0.13961507, 0.69181876],
        [0.77687712, 0.78391431, 0.21725696, 0.90570822]]))

In [12]:
matrix_3x4 = np.random.randint(1, 11, (3, 4))
vector = np.random.randint(1, 11, 4)

result = np.dot(matrix_3x4, vector)
("Матриця 3x4:\n", matrix_3x4)
("Вектор:\n", vector)
("Результат множення:\n", result)

('Результат множення:\n', array([122, 150,  65], dtype=int32))